//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searchfight {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Searchfight : global::System.Configuration.ApplicationSettingsBase {
        
        private static Searchfight defaultInstance = ((Searchfight)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Searchfight())));
        
        public static Searchfight Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google")]
        public string Buscador1 {
            get {
                return ((string)(this["Buscador1"]));
            }
            set {
                this["Buscador1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSN Search")]
        public string Buscador2 {
            get {
                return ((string)(this["Buscador2"]));
            }
            set {
                this["Buscador2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.google.com/search")]
        public string Direccion1 {
            get {
                return ((string)(this["Direccion1"]));
            }
            set {
                this["Direccion1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.bing.com/search")]
        public string Direccion2 {
            get {
                return ((string)(this["Direccion2"]));
            }
            set {
                this["Direccion2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Cerca de \"")]
        public string CadenaIni1 {
            get {
                return ((string)(this["CadenaIni1"]));
            }
            set {
                this["CadenaIni1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" resultados\"")]
        public string CadenaFin1 {
            get {
                return ((string)(this["CadenaFin1"]));
            }
            set {
                this["CadenaFin1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"sb_count\\\">\"")]
        public string CadenaIni2 {
            get {
                return ((string)(this["CadenaIni2"]));
            }
            set {
                this["CadenaIni2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" resultados\"")]
        public string CadenaFin2 {
            get {
                return ((string)(this["CadenaFin2"]));
            }
            set {
                this["CadenaFin2"] = value;
            }
        }
    }
}
